<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType><AssemblyName>meleemap</AssemblyName>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../MeleeMap.Core/MeleeMap.Core.csproj" /></ItemGroup>
</Project>
